# Generated by Django 6.0.5 on 2026-06-01 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('homesports', '0002_categoria_moto_categoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='moto',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='motos/'),
        ),
    ]
